# Generated by Django 3.0.4 on 2020-04-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globe', '0003_myprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(default='pic02.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
