# Generated by Django 3.0.4 on 2020-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globe', '0004_auto_20200423_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
