# Generated by Django 3.0.4 on 2020-04-24 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Globe', '0008_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 11, 37, 48, 487222, tzinfo=utc)),
        ),
    ]
