# Generated by Django 3.0.4 on 2020-05-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Globe', '0015_auto_20200501_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
    ]
