# Generated by Django 3.0.4 on 2020-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globe', '0023_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscussionTopic',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
